import { NextResponse } from "next/server";
import { requireAuth } from "@/lib/rbac";
import { firestore } from "@/lib/firebase-admin";

export const runtime = "nodejs";

const parseBody = async (req) => {
  try {
    return await req.json();
  } catch {
    return {};
  }
};

const normalizeText = (value) => String(value || "").trim();

export async function GET(req) {
  const gate = await requireAuth(req);
  if (!gate.ok) return gate.res;

  const { searchParams } = new URL(req.url);
  const targetUserId = normalizeText(searchParams.get("userId")) || gate.auth.user.id;

  if (!firestore) {
    return NextResponse.json(
      { error: "Firestore admin SDK is not initialized." },
      { status: 503 },
    );
  }

  const snapshot = await firestore
    .collection("notifications")
    .doc(targetUserId)
    .collection("items")
    .orderBy("createdAt", "desc")
    .limit(5)
    .get();

  return NextResponse.json({
    ok: true,
    targetUserId,
    count: snapshot.size,
    items: snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })),
  });
}

export async function POST(req) {
  const gate = await requireAuth(req);
  if (!gate.ok) return gate.res;

  const body = await parseBody(req);
  const targetUserId = normalizeText(body.userId) || gate.auth.user.id;
  const title = normalizeText(body.title) || "Debug Notification";
  const message =
    normalizeText(body.message) ||
    "This is a Firestore debug notification generated by /api/debug/notifications.";

  if (!firestore) {
    return NextResponse.json(
      { error: "Firestore admin SDK is not initialized." },
      { status: 503 },
    );
  }

  const collectionRef = firestore
    .collection("notifications")
    .doc(targetUserId)
    .collection("items");

  const docRef = await collectionRef.add({
    title,
    message,
    createdAt: new Date(),
    isRead: false,
    debug: true,
    createdById: gate.auth.user.id,
  });

  const writtenDoc = await docRef.get();
  const latestSnapshot = await collectionRef
    .orderBy("createdAt", "desc")
    .limit(5)
    .get();

  return NextResponse.json({
    ok: true,
    targetUserId,
    path: docRef.path,
    written: {
      id: writtenDoc.id,
      exists: writtenDoc.exists,
      data: writtenDoc.data(),
    },
    recentCount: latestSnapshot.size,
    recentItems: latestSnapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })),
  });
}
